# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gHssgYUs3AAwfUBS5n_NAYWh9Pz2U4gC
"""

import string
import random

def generate_password(length=8):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def validate_password_strength(password):
    # Check if password has at least one lowercase letter
    if not any(char.islower() for char in password):
        return False

    # Check if password has at least one uppercase letter
    if not any(char.isupper() for char in password):
        return False

    # Check if password has at least one digit
    if not any(char.isdigit() for char in password):
        return False

    # Check if password has at least one punctuation character
    if not any(char in string.punctuation for char in password):
        return False

    return True

# Generate a password of length 10
password = generate_password(10)
print("Generated Password:", password)

# Validate the strength of the password
is_strong = validate_password_strength(password)
strength = "Strong" if is_strong else "Weak"
print("Password Strength:", strength)